### ISSUE TITLE
Charm is deducing the executor tag based on the tag of the controller image

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/argo-operators#115]
The Charm is deducing what executor image to use based on the tag of the controller image. This is error prone and expects a specific tagging for both images. 

We should instead have this whole image configurable, via the `config.yaml` file. This also limits our airgapped story, since we can't define a different registry for the image.

https://github.com/canonical/argo-operators/blob/0d80f2a614ec1d7421f47d9ad6af9ec4f4c87dab/charms/argo-controller/src/charm.py#L82-L85

**Comment by orfeas-k** [comment]
We need to merge this https://github.com/canonical/argo-operators/pull/125 before proceeding with https://github.com/canonical/bundle-kubeflow/issues/680.
